# Generated by Django 3.0.8 on 2020-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=150, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='负责人', max_length=50, verbose_name='负责人')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('developer', models.CharField(help_text='开发人员', max_length=50, verbose_name='开发人员')),
                ('desc', models.TextField(blank=True, default='', help_text='项目描述', null=True, verbose_name='项目描述')),
            ],
        ),
    ]
