# Generated by Django 3.0.8 on 2020-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200726_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
